#!/bin/bash

#SBATCH -n 16                              # Number of cores
#SBATCH --time=16:00:00                    # hours:minutes:seconds
#SBATCH --mem-per-cpu=2000
#SBATCH --tmp=4000                         # per node!!
#SBATCH --gpus=1                           # Ohter options are: --gpus=gtx_1080_ti:1  --gpus=rtx_2080_ti:1
#SBATCH --job-name=gpu_job
#SBATCH --output=./jobs/gpu_job.out
#SBATCH --error=./jobs/gpu_job.err


#env2lmod
#module load gcc/8.2.0 python_gpu/3.10.4

source $HOME/venvs/simpleEnvGpu/bin/activate
python3 ./src/test_gpu.py
